### ISSUE TITLE
Remove the pre-emptive error if section not chosen

### ISSUE THREAD

**Issue by imtixz** [MHThe1/automate-routine-frontend#1]
Since you're limiting the "too many combinations" error on the backend anyway, you could remove the frontend restrictions on running generate without choosing section since choosing faculty could also reduce the number of combinations. Current version doesnt allow me to run generate where i mention subjects and faculties (which should still have a less enough number of sections to start the routine generation process)

**Comment by MHThe1** [comment]
> Since you're limiting the "too many combinations" error on the backend anyway, you could remove the frontend restrictions on running generate without choosing section since choosing faculty could also reduce the number of combinations. Current version doesnt allow me to run generate where i mention subjects and faculties (which should still have a less enough number of sections to start the routine generation process)

I'm not limiting "too many combinations" in the backend, it's just that when the combinations get's too large the backend takes more time naturally but my free hosting service only sends the data back if it's all done in a certain amount of time and thus I'm limiting it in the frontend so there are less errors. But yeah I could set this as a soft warning instead of not letting users click generate button. (note that, I created this system before implementing the faculty choosing feature, thus didn't take this into account at that point)

**Comment by MHThe1** [comment]
In the updated frontend, I only warn users regarding regarding requests that may fail due to their size in the backend. Thus I'm closing this issue. Thank you
